#!/bin/bash
ls

# Syntax: Command Option(flag) Argument

# Command: ls
# Option: -F (display file type) | -l (list in long format) | -a (list hidden files)
# Arguments: * (Wildcards) | directoty-name
