#!/bin/bash
ls

# Syntax: command option(flag) argument

# Command: ls
# Option: -F (display file type) | -l (list in long format) | -a (list hidden files)
# Arguments: * (Wildcards) | directoty-name
