#!/bin/bash
head -n 4 /etc/passwd | tail -n 1

# The most useful and powerful thing we can do with I/O redirection is to 
# connect multiple commands together to form what are called pipelines.
# With pipelines, the standard output of one command is fed into the 
# standard input of another.
