#!/bin/bash
echo {2017..2019}-{01..12}

#Brace Expansion can create multiple text strings from a pattern containing braces.
#The most common application is to make lists of files or directories to be created. For example, if we were a photographer and had a large collection of images we wanted to organise into years and months, the first thing we might do is create a series of directories named in numeric “Year-Month” format. This way, the directory names will sort in chronological order. we could type out a complete list of directories, but that's a lot of work and it's error-prone too. Instead, we could use brace expansion.
